### ISSUE TITLE
Provide mock data from storybook gui

### ISSUE THREAD

**Issue by asherccohen** [itaditya/msw-storybook-addon#11]
I just discovered this awesome add-on, great job!

I plan to use it in a project and haven't experimented with it yet, would it be possible to provide mock data from the storybook gui (like we do with the controls addon for example).

This would be interesting as it would let the users (or product owners/sales managers) test some data without touching code.

I'm asking because the data that I display in my apps is very complex (data viz), and usually the result of a calculation on the backend.

**Comment by itaditya** [comment]
Hey @asherccohen glad you liked my addon. Your idea looked useful to me so I tried to implement it.

https://github.com/itaditya/msw-storybook-addon/pull/12/files

As you can see in the PR, whatever args you provide to the story, can be accessed in the `msw` parameter and used in the response. 

### But there is a big problem.

When the args changes, the mock handler will update its response. However, the API call is already done, unless it is triggered again, the UI will stay the same.

In my PR, I have shown a fetch example that makes API calls when `triggerRefetch` arg's value changes. This is not a good solution since now the component's internal code is changed to work in Storybook and each library would need different code to clear cache & re-fetch API data.

### Concluding Thoughts

I think the simplest approach right now would be to export different stories with different mock responses that show all the situations your Product Owners care about.

If in case a particular UI piece would require tonnes of mock handlers to document all behaviors in that situation you should break the component into Container/Presentational. Then use the Presentational component in the story and connect it with args.

**Comment by asherccohen** [comment]
Thanks!and sorry for the late reply.

You saved me a couple of hours of digging, very much appreciated.

I will experiment a bit more and then come back to you!

**Comment by elpddev** [comment]
For now, I use ctx for transfering data between storybook args and msw.

* In the main preview decorator, I get `parameters` and set `parameters.msw.handlers.appConfig.__mydata` to some data, * and in the handler I get the data from the `ctx` argument.
